version: 2

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - unused

formatters:
  enable:
    - gofmt
    - gofumpt
    - gci
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/InTeamDev)
