// Package adminapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package adminapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Building defines model for Building.
type Building struct {
	Address *string             `json:"address,omitempty"`
	Id      *openapi_types.UUID `json:"id,omitempty"`
	Name    *string             `json:"name,omitempty"`
}

// CreateBuilding defines model for CreateBuilding.
type CreateBuilding struct {
	Address *string `json:"address,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// CreateObjectInput defines model for CreateObjectInput.
type CreateObjectInput struct {
	Alias        *string             `json:"alias,omitempty"`
	Description  *string             `json:"description,omitempty"`
	Height       *float32            `json:"height,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Name         *string             `json:"name,omitempty"`
	ObjectTypeId *int                `json:"object_type_id,omitempty"`
	Width        *float32            `json:"width,omitempty"`
	X            *float32            `json:"x,omitempty"`
	Y            *float32            `json:"y,omitempty"`
}

// Door defines model for Door.
type Door struct {
	Height   *float32            `json:"height,omitempty"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	ObjectId *openapi_types.UUID `json:"object_id,omitempty"`
	Width    *float32            `json:"width,omitempty"`
	X        *float32            `json:"x,omitempty"`
	Y        *float32            `json:"y,omitempty"`
}

// Floor defines model for Floor.
type Floor struct {
	Alias *string             `json:"alias,omitempty"`
	Id    *openapi_types.UUID `json:"id,omitempty"`
	Name  *string             `json:"name,omitempty"`
}

// Object defines model for Object.
type Object struct {
	Alias        *string             `json:"alias,omitempty"`
	Description  *string             `json:"description,omitempty"`
	Doors        *[]Door             `json:"doors,omitempty"`
	Floor        *Floor              `json:"floor,omitempty"`
	Height       *float32            `json:"height,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Name         *string             `json:"name,omitempty"`
	ObjectTypeId *int                `json:"object_type_id,omitempty"`
	Width        *float32            `json:"width,omitempty"`
	X            *float32            `json:"x,omitempty"`
	Y            *float32            `json:"y,omitempty"`
}

// UpdateBuildingInput defines model for UpdateBuildingInput.
type UpdateBuildingInput struct {
	Address *string `json:"address,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// UpdateObjectInput defines model for UpdateObjectInput.
type UpdateObjectInput struct {
	Alias        *string  `json:"alias,omitempty"`
	Description  *string  `json:"description,omitempty"`
	Height       *float32 `json:"height,omitempty"`
	Name         *string  `json:"name,omitempty"`
	ObjectTypeId *int     `json:"object_type_id,omitempty"`
	Width        *float32 `json:"width,omitempty"`
	X            *float32 `json:"x,omitempty"`
	Y            *float32 `json:"y,omitempty"`
}

// PostBuildingsJSONRequestBody defines body for PostBuildings for application/json ContentType.
type PostBuildingsJSONRequestBody = CreateBuilding

// PatchBuildingsBuildingIdJSONRequestBody defines body for PatchBuildingsBuildingId for application/json ContentType.
type PatchBuildingsBuildingIdJSONRequestBody = UpdateBuildingInput

// PostBuildingsBuildingIdFloorsFloorIdObjectsJSONRequestBody defines body for PostBuildingsBuildingIdFloorsFloorIdObjects for application/json ContentType.
type PostBuildingsBuildingIdFloorsFloorIdObjectsJSONRequestBody = CreateObjectInput

// PatchObjectsObjectIdJSONRequestBody defines body for PatchObjectsObjectId for application/json ContentType.
type PatchObjectsObjectIdJSONRequestBody = UpdateObjectInput
