// Package authapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package authapi

// PostSaveTgUserJSONBody defines parameters for PostSaveTgUser.
type PostSaveTgUserJSONBody struct {
	TgId       *int    `json:"tg_id,omitempty"`
	TgUsername *string `json:"tg_username,omitempty"`
}

// PostSendCodeJSONBody defines parameters for PostSendCode.
type PostSendCodeJSONBody struct {
	TgUsername *string `json:"tg_username,omitempty"`
}

// PostVerifyJSONBody defines parameters for PostVerify.
type PostVerifyJSONBody struct {
	Code       *string `json:"code,omitempty"`
	TgUsername *string `json:"tg_username,omitempty"`
}

// PostSaveTgUserJSONRequestBody defines body for PostSaveTgUser for application/json ContentType.
type PostSaveTgUserJSONRequestBody PostSaveTgUserJSONBody

// PostSendCodeJSONRequestBody defines body for PostSendCode for application/json ContentType.
type PostSendCodeJSONRequestBody PostSendCodeJSONBody

// PostVerifyJSONRequestBody defines body for PostVerify for application/json ContentType.
type PostVerifyJSONRequestBody PostVerifyJSONBody
