// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/google/uuid"
)

type Connection struct {
	FromID uuid.UUID
	ToID   uuid.UUID
	Weight float64
}

type Intersection struct {
	ID      uuid.UUID
	X       float64
	Y       float64
	FloorID uuid.UUID
}
