server:
  host: "0.0.0.0"
  port: 8001
jwt_secret: "secret"
bot_client:
  url: "http://localhost:8090"
  client_id: "service"
  access_token: "secret"
auth:
  client_id: "service"
  access_token: "secret"
