name: Go CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Lint & Test
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b "$(go env GOPATH)/bin" v1.64.8
          golangci-lint run --out-format=colored-line-number
          go test ./... -v

      - name: Build Docker images
        run: |
          docker build --build-arg SERVICE=publicapi -t ${{ secrets.REGISTRY_USER }}/utmn-map-backend-publicapi:latest .
          docker build --build-arg SERVICE=adminapi  -t ${{ secrets.REGISTRY_USER }}/utmn-map-backend-adminapi:latest .

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push images
        run: |
          docker push ${{ secrets.REGISTRY_USER }}/utmn-map-backend-publicapi:latest
          docker push ${{ secrets.REGISTRY_USER }}/utmn-map-backend-adminapi:latest
