// Package publicapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package publicapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BackgroundPoint defines model for BackgroundPoint.
type BackgroundPoint struct {
	Order *int     `json:"order,omitempty"`
	X     *float32 `json:"x,omitempty"`
	Y     *float32 `json:"y,omitempty"`
}

// Building defines model for Building.
type Building struct {
	Address *string             `json:"address,omitempty"`
	Id      *openapi_types.UUID `json:"id,omitempty"`
	Name    *string             `json:"name,omitempty"`
}

// Door defines model for Door.
type Door struct {
	Height   *float32            `json:"height,omitempty"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	ObjectId *openapi_types.UUID `json:"object_id,omitempty"`
	Width    *float32            `json:"width,omitempty"`
	X        *float32            `json:"x,omitempty"`
	Y        *float32            `json:"y,omitempty"`
}

// Floor defines model for Floor.
type Floor struct {
	Alias *string             `json:"alias,omitempty"`
	Id    *openapi_types.UUID `json:"id,omitempty"`
	Name  *string             `json:"name,omitempty"`
}

// FloorBackgroundElement defines model for FloorBackgroundElement.
type FloorBackgroundElement struct {
	Id     *openapi_types.UUID `json:"id,omitempty"`
	Label  *string             `json:"label,omitempty"`
	Points *[]BackgroundPoint  `json:"points,omitempty"`
	ZIndex *int                `json:"z_index,omitempty"`
}

// FloorWithData defines model for FloorWithData.
type FloorWithData struct {
	Background *[]FloorBackgroundElement `json:"background,omitempty"`
	Floor      *Floor                    `json:"floor,omitempty"`
	Objects    *[]Object                 `json:"objects,omitempty"`
}

// GetObjectsResponse defines model for GetObjectsResponse.
type GetObjectsResponse struct {
	Building *Building        `json:"building,omitempty"`
	Floors   *[]FloorWithData `json:"floors,omitempty"`
}

// Object defines model for Object.
type Object struct {
	Alias        *string             `json:"alias,omitempty"`
	Description  *string             `json:"description,omitempty"`
	Doors        *[]Door             `json:"doors,omitempty"`
	Floor        *Floor              `json:"floor,omitempty"`
	Height       *float32            `json:"height,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Name         *string             `json:"name,omitempty"`
	ObjectTypeId *int                `json:"object_type_id,omitempty"`
	Width        *float32            `json:"width,omitempty"`
	X            *float32            `json:"x,omitempty"`
	Y            *float32            `json:"y,omitempty"`
}

// ObjectTypeInfo defines model for ObjectTypeInfo.
type ObjectTypeInfo struct {
	Alias *string `json:"alias,omitempty"`
	Id    *int    `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Category *string             `json:"category,omitempty"`
	ObjectId *openapi_types.UUID `json:"object_id,omitempty"`
	Preview  *string             `json:"preview,omitempty"`
}

// GetBuildingsBuildIdSearchParams defines parameters for GetBuildingsBuildIdSearch.
type GetBuildingsBuildIdSearchParams struct {
	Query    *string   `form:"query,omitempty" json:"query,omitempty"`
	Category *[]string `form:"category,omitempty" json:"category,omitempty"`
}
